import { printToFileAsync } from 'expo-print';
import { shareAsync } from 'expo-sharing';
import { getDownloadURL, ref, uploadBytes } from 'firebase/storage';
import { formatZAR } from '../lib/money';
import { storage } from './firebase';

const generateHTML = (title: string, inputs: Record<string, any>, results: Record<string, any>) => {
  const inputRows = Object.entries(inputs).map(([key, value]) => `
    <tr>
      <td style="padding: 8px; border-bottom: 1px solid #eee; color: #666; text-transform: capitalize;">${key.replace(/([A-Z])/g, ' $1').trim()}</td>
      <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold; text-align: right;">${typeof value === 'number' ? formatZAR(value) : value}</td>
    </tr>
  `).join('');

  const resultRows = Object.entries(results).map(([key, value]) => `
    <tr>
      <td style="padding: 8px; border-bottom: 1px solid #eee; color: #666; text-transform: capitalize;">${key.replace(/([A-Z])/g, ' $1').trim()}</td>
      <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold; text-align: right;">${typeof value === 'number' ? formatZAR(value) : value}</td>
    </tr>
  `).join('');

  return `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 20px; color: #333; }
          h1 { color: #0A5C3B; text-align: center; margin-bottom: 10px; }
          h2 { color: #333; border-bottom: 2px solid #0A5C3B; padding-bottom: 5px; margin-top: 20px; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; }
          .footer { margin-top: 40px; text-align: center; color: #999; font-size: 12px; }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <p style="text-align: center; color: #666;">Generated by PnP Conveyancing</p>
        
        <h2>Inputs</h2>
        <table>
          ${inputRows}
        </table>

        <h2>Results</h2>
        <table>
          ${resultRows}
        </table>

        <div class="footer">
          <p>Disclaimer: This calculation is an estimate and for information purposes only.</p>
          <p>${new Date().toLocaleDateString()}</p>
        </div>
      </body>
    </html>
  `;
};

export const generateAndSharePDF = async (title: string, inputs: any, results: any) => {
  try {
    const html = generateHTML(title, inputs, results);
    const { uri } = await printToFileAsync({ html });
    await shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
};

/**
 * Generates a PDF and uploads it to Firebase Storage.
 * Returns the download URL of the uploaded file.
 */
export const generateAndSavePDF = async (title: string, inputs: any, results: any, userId: string): Promise<string> => {
  try {
    // 1. Generate HTML and Print to PDF file locally
    const html = generateHTML(title, inputs, results);
    const { uri } = await printToFileAsync({ html });

    // 2. Convert URI to Blob
    const response = await fetch(uri);
    const blob = await response.blob();

    // 3. Create a reference in Firebase Storage
    // Path: pdfs/{userId}/{timestamp}_{title}.pdf
    const sanitizedTitle = title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    const filename = `${Date.now()}_${sanitizedTitle}.pdf`;
    const storageRef = ref(storage, `pdfs/${userId}/${filename}`);

    // 4. Upload the Blob
    await uploadBytes(storageRef, blob);

    // 5. Get and return the download URL
    const downloadURL = await getDownloadURL(storageRef);
    return downloadURL;

  } catch (error) {
    console.error('Error saving PDF to Firebase:', error);
    throw error;
  }
};
